### ISSUE TITLE
Request stub not immediately returning response on jquery load

### ISSUE THREAD

**Issue by DavidGrinberg** [jasmine/jasmine-ajax#159] opened 2016-07-12 19:23 UTC
I have some code that, simplified, looks like - 

```
init = function(){
  $("#foo").load("some/path.html", function(){
      setSomeGlobalVar();
  });
}
```

I'm trying to test it with code like - 

```
describe("foo test", function(){
  beforeEach(function(){
    jasmine.Ajax.install();
    jasmine.Ajax.stubRequest('some/path.html').andReturn({
      contentType: 'text/plain',
      responseText: '<bar/>'
    });

  afterEach(function(){
    jasmine.Ajax.uninstall();
  });

  it("", function(){
      init();
      expectGlobalVarToBeSet();//fails because load callback hasn't been called yet
  }
});
```

This test is failing though. For some reason the stub does not respond until after the it block completes, when its too late for the expectation.

Why is this and how do I get the response to trigger synchronously?

**Comment by nicklandgrebe** [comment] 2016-09-12 22:44
+1

**Comment by DarioG** [comment] 2016-09-13 09:18
Maybe jquery is making any kind of magic behind the hood. I suggest to approach the issue in a different way:

```
init = function(){
  $("#foo").load("some/path.html", function(){
      setSomeGlobalVar();
  });
}

it("", function(){
      spyOn($("#foo"), 'load').and.callFake(function (path, callback) {
      	if (path === "some/path.html") {
      		callback();
      	}
      });
      
      init();
      expectGlobalVarToBeSet();//fails because load callback hasn't been called yet
  }
```

**Comment by nicklandgrebe** [comment] 2016-09-15 04:03
@DarioG was on to something. I confirmed that jQuery was in fact the problem like so:

```
# $.ajax ... # my old jQuery call that lags

# instead:
xhttp = new XMLHttpRequest()
        xhttp.onreadystatechange = ->
          debugger

        xhttp.open("GET", '/api/v1/products', true)
        xhttp.send()

        jasmine.Ajax.requests.mostRecent().respondWith(JsonApiResponses.Product.all.success)
        debugger
        # expect(window.onSuccess).toHaveBeenCalled() # my old expectation that the jQuery callback executed
```

I then ran this in browser with console, and sure enough, the `onreadystatechange` callback executed all the way to `readyState=4` (finished) before we reached the debugger that precedes the expectation that my jQuery callback was called. Previously, I would reach this expectation before I would reach a single debugger in my jQuery callback.

Turns out, jQuery 3.0 made changes to Deferred, and this must have broken something. So I rolled back to jQuery 2.2.4 in package.json:

```
"dependencies": {
    "jquery": "2.2.4"
}
```

and ran `npm install jquery@2.2.4`

All my tests pass now! Thanks for the hint, @DarioG

**Comment by slackersoft** [comment] 2016-09-15 16:18
It sounds like this is an issue with jQuery and not Jasmine-Ajax, so I'm going to close this issue. Please let us know if you discover something that Jasmine-Ajax is doing that is causing issues like this.

Thanks for using Jasmine!

**Closed by slackersoft** 2016-09-15 16:18 UTC
