### ISSUE TITLE
TypeError: Cannot read property 'install' of undefined

### ISSUE THREAD

**Issue by speasley** [jasmine/jasmine-ajax#101] opened 2015-04-04 23:02 UTC
I have a Rails setup with Teaspoon (which runs Jasmine 1.3.1) and CoffeeScript. I have placed the `mock-ajax.js` (1.3.1) in my `helpers` directory. I have verified that the folder is included in `jasmine.yml`. On my `jasmine.Ajax.install()`call, I am greeted with `TypeError: Cannot read property 'install' of undefined`. I've tried placing the file inside `support` instead, I've tried including it as a `require` in the Jasmine spec helper. I've tried the 1.3.1 instructions and end up with a similar error (`TypeError: Cannot read property 'useMock' of undefined`). It seems as though `mock-ajax.js` is not even been loaded and I cannot figure out why. Anyone?

**Comment by slackersoft** [comment] 2015-04-06 20:04
Can you verify that the browser is even downloading the mock-ajax.js script and parsing it properly? Are you seeing any javascript errors when the page loads? It sounds like there might be something causing the file not to execute correctly.

**Comment by speasley** [comment] 2015-04-06 23:57
The file is not being loaded in at all. I have verified the paths and the existence of the file.

**Comment by slackersoft** [comment] 2015-04-08 23:13
If the file is not being loaded on the page at all, it sounds like an issue with Teaspoon and not jasmine-ajax.

Have you tried using the [jasmine gem](https://rubygems.org/gems/jasmine)? It can start a server with asset pipeline support and use phantomjs to run your specs in a CI environment.

**Comment by tkiddle** [comment] 2015-04-19 08:46
Hi had a similar issue. My issue was caused by the wrong permissions on the mock-ajax.js file.

**Comment by asiniy** [comment] 2015-09-04 10:58
+1

**Comment by slackersoft** [comment] 2015-10-15 19:40
It sounds like this is generally an issue with a third party serving the `mock-ajax.js` and not with jasmine-ajax itself, so I'm going to close this.

Thanks for using jasmine!

**Closed by slackersoft** 2015-10-15 19:40 UTC
Labels: waiting
