### ISSUE TITLE
Success handler is invoked sync, but request is async.

### ISSUE THREAD

**Issue by AlexanderShushunov** [jasmine/jasmine-ajax#138] opened 2015-11-05 09:56 UTC
If I use `jasmine.Ajax.stubRequest(..).andReturn(..)` handlers are invoked in the same call stack as  `xhr.send()`.
This test failed:
```javascript
describe("Jasmine mock-ajax", function () {
	var SOME_URL = "request-url";
	beforeEach(function () {
		jasmine.Ajax.install();
		jasmine.Ajax.stubRequest(SOME_URL).andReturn({
			status: 200,
			statusText: "HTTP/1.1 200 OK"
		});
	});
	afterEach(function () {
		jasmine.Ajax.uninstall();
	});
	it("should call handler async", function () {
		var doneFn = jasmine.createSpy("success");
		var xhr = new XMLHttpRequest();
		xhr.onreadystatechange = function () {
			if (this.readyState == this.DONE) {
				doneFn(this.responseText);
			}
		};
		xhr.open("GET", SOME_URL);
		xhr.send();
		expect(doneFn).not.toHaveBeenCalled();
	});
});
```

**Comment by slackersoft** [comment] 2015-11-14 01:20
That is the intended behavior when using `stubRequest`. This feature is designed for when you are trying to test what occurs after the AJAX call completes. If you want to test the state of your application in between when the request is made and when the response comes back, you don't want to use `stubRequest`, but call `jasmine.Ajax.requests.mostRecent().respondWith(..)` after you have done whatever verification you need.

Thanks for using jasmine! Closing this.

**Closed by slackersoft** 2015-11-14 01:20 UTC
